version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "julia"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    exclude-paths:
      - "test/**"
      - "docs/**"
      - "benchmarks/**"
      - "KomaMRIBase/test/**"
      - "KomaMRICore/test/**"
      - "KomaMRIFiles/test/**"
      - "KomaMRIPlots/test/**"
    labels:
      - "dependencies"
      - "julia"
