name = "KomaMRIPlots"
uuid = "76db0263-63f3-4d26-bb9a-5dba378db904"
authors = ["Carlos Castillo Passi <cncastillo@uc.cl>"]
version = "0.7.8"

[deps]
KomaMRICore = "4baa4f4d-2ae9-40db-8331-a7d1080e3f4e"

[compat]
KomaMRICore = "0.7"
julia = "1.6"
