steps:
  - label: ":pipeline: Launch Tests"
    command: buildkite-agent pipeline upload .buildkite/runtests.yml
    agents:
      queue: "juliagpu"

  - label: ":pipeline: Launch Benchmarks"
    if: build.message !~ /skip benchmarks/
    agents:
      queue: "juliagpu"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: ".buildkite/scripts/diff.sh $BUILDKITE_COMMIT"
          interpolation: false
          watch:
            - path:
                - "KomaMRICore/src/**"
                - "KomaMRICore/ext/**"
                - "KomaMRICore/Project.toml"
                - "KomaMRIBase/src/**"
                - "KomaMRICore/Project.toml"
                - "bench/**"
                - ".buildkite/**"
                - "Project.toml"
              config:
                command: "buildkite-agent pipeline upload .buildkite/runbenchmarks.yml"
                agents:
                  queue: "juliagpu"
