steps:
  - label: ":pipeline: Launch Tests"
    command: buildkite-agent pipeline upload .buildkite/runtests.yml
    agents:
      queue: "juliaecosystem"
      sandbox_capable: true

  #To-do: update to only trigger on push to main or first pull request commit
  - label: ":pipeline: Launch Benchmarks"
    command: buildkite-agent pipeline upload .buildkite/runbenchmarks.yml
    agents:
      queue: "juliaecosystem"
      sandbox_capable: true
