steps:
  - label: ":pipeline: Launch Tests"
    command: buildkite-agent pipeline upload .buildkite/runtests.yml
    agents:
      queue: "juliagpu"

  - label: ":pipeline: Launch Benchmarks"
    if: build.message !~ /skip benchmarks/
    agents:
      queue: "juliagpu"
    plugins:
      - monebag/monorepo-diff#v2.5.9:
          diff: ".buildkite/scripts/diff.sh $BUILDKITE_COMMIT"
          log_level: "debug"
          interpolation: false
          watch:
            - path:
                - "KomaMRICore/src/"
                - "KomaMRICore/ext/"
                - "KomaMRICore/Project.toml"
                - "KomaMRIBase/src/"
                - "KomaMRICore/Project.toml"
                - "bench/"
                - ".buildkite/"
                - "Project.toml"
              config:
                command: "buildkite-agent pipeline upload .buildkite/runbenchmarks.yml"
                agents:
                  queue: "juliagpu"
