steps:
  - label: ":pipeline: Upload NoMotion Tests"
    if: build.pull_request.labels includes "run-gpu-ci" || build.branch == "master"
    plugins:
      - sparse-checkout#v1.8.0:
          paths:
            - .buildkite
    env:
      TEST_GROUP: "nomotion"
    command: buildkite-agent pipeline upload .buildkite/runtests.yml
    agents:
      queue: upload

  - label: ":pipeline: Upload Motion Tests"
    if: build.pull_request.labels includes "run-gpu-ci" || build.branch == "master"
    plugins:
      - sparse-checkout#v1.8.0:
          paths:
            - .buildkite
    env:
      TEST_GROUP: "motion"
    command: buildkite-agent pipeline upload .buildkite/runtests.yml
    agents:
      queue: upload

  - label: ":pipeline: Launch Benchmarks"
    if: |
      build.branch == "master" ||
        (
          build.pull_request.labels includes "run-gpu-ci" &&
          !build.pull_request.repository.fork &&
          build.branch !~ /^dependabot\//
        )
    plugins:
      - sparse-checkout#v1.8.0:
          paths:
            - .buildkite
          # Fetch commit history so HEAD~1 is available to the diff below.
          post_checkout:
            unshallow: true
    command: |
      if ! git diff --quiet HEAD~1 -- \
        KomaMRICore/src \
        KomaMRICore/ext \
        KomaMRICore/Project.toml \
        KomaMRIBase/src \
        KomaMRIBase/Project.toml \
        benchmarks \
        .buildkite \
        .github/workflows/Benchmark.yml \
        Project.toml
      then
        buildkite-agent pipeline upload .buildkite/runbenchmarks.yml
      fi
    agents:
      queue: upload
