steps:
  - label: "KomaMRICore / Benchmark / CPU 1T / Julia 1"
    key: "benchmark-cpu-1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=benchmarks -e 'println("--- :julia: Instantiating project")
          using Pkg
          Pkg.develop([
              PackageSpec(path=pwd(), subdir="KomaMRIBase"),
              PackageSpec(path=pwd(), subdir="KomaMRICore"),
          ])'

      julia --project=benchmarks -e 'println("--- :julia: Run Benchmarks")
          include("benchmarks/runbenchmarks.jl")'
    artifact_paths:
      - "benchmarks/results/*"
    agents:
      arch: "aarch64"
      queue: "juliaecosystem"
      num_cpus: "8"
    env:
      BENCHMARK_GROUP: CPU
      JULIA_NUM_THREADS: "1"
    timeout_in_minutes: 30

  - label: "KomaMRICore / Benchmark / CPU 2T / Julia 1"
    key: "benchmark-cpu-2"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=benchmarks -e 'println("--- :julia: Instantiating project")
          using Pkg
          Pkg.develop([
              PackageSpec(path=pwd(), subdir="KomaMRIBase"),
              PackageSpec(path=pwd(), subdir="KomaMRICore"),
          ])'

      julia --project=benchmarks -e 'println("--- :julia: Run Benchmarks")
          include("benchmarks/runbenchmarks.jl")'
    artifact_paths:
      - "benchmarks/results/*"
    agents:
      arch: "aarch64"
      queue: "juliaecosystem"
      num_cpus: "8"
    env:
      BENCHMARK_GROUP: CPU
      JULIA_NUM_THREADS: "2"
    timeout_in_minutes: 30

  - label: "KomaMRICore / Benchmark / CPU 4T / Julia 1"
    key: "benchmark-cpu-4"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=benchmarks -e 'println("--- :julia: Instantiating project")
          using Pkg
          Pkg.develop([
              PackageSpec(path=pwd(), subdir="KomaMRIBase"),
              PackageSpec(path=pwd(), subdir="KomaMRICore"),
          ])'

      julia --project=benchmarks -e 'println("--- :julia: Run Benchmarks")
          include("benchmarks/runbenchmarks.jl")'
    artifact_paths:
      - "benchmarks/results/*"
    agents:
      arch: "aarch64"
      queue: "juliaecosystem"
      num_cpus: "8"
    env:
      BENCHMARK_GROUP: CPU
      JULIA_NUM_THREADS: "4"
    timeout_in_minutes: 30

  - label: "KomaMRICore / Benchmark / CPU 8T / Julia 1"
    key: "benchmark-cpu-8"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=benchmarks -e 'println("--- :julia: Instantiating project")
          using Pkg
          Pkg.develop([
              PackageSpec(path=pwd(), subdir="KomaMRIBase"),
              PackageSpec(path=pwd(), subdir="KomaMRICore"),
          ])'

      julia --project=benchmarks -e 'println("--- :julia: Run Benchmarks")
          include("benchmarks/runbenchmarks.jl")'
    artifact_paths:
      - "benchmarks/results/*"
    agents:
      arch: "aarch64"
      queue: "juliaecosystem"
      num_cpus: "8"
    env:
      BENCHMARK_GROUP: CPU
      JULIA_NUM_THREADS: "8"
    timeout_in_minutes: 30

  - label: "KomaMRICore / Benchmark / AMDGPU / Julia 1"
    key: "benchmark-amdgpu"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=benchmarks -e 'println("--- :julia: Instantiating project")
          using Pkg
          Pkg.develop([
              PackageSpec(path=pwd(), subdir="KomaMRIBase"),
              PackageSpec(path=pwd(), subdir="KomaMRICore"),
          ])'

      julia --project=benchmarks -e 'println("---:julia: Add AMDGPU to benchmarks environment")
          using Pkg
          Pkg.add("AMDGPU")'

      julia --project=benchmarks -e 'println("--- :julia: Run Benchmarks")
          include("benchmarks/runbenchmarks.jl")'
    artifact_paths:
      - "benchmarks/results/*"
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "gfx1100"
    env:
      BENCHMARK_GROUP: AMDGPU
    timeout_in_minutes: 30

  - label: "KomaMRICore / Benchmark / CUDA / Julia 1"
    key: "benchmark-cuda"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=benchmarks -e 'println("--- :julia: Instantiating project")
          using Pkg
          Pkg.develop([
              PackageSpec(path=pwd(), subdir="KomaMRIBase"),
              PackageSpec(path=pwd(), subdir="KomaMRICore"),
          ])'

      julia --project=benchmarks -e 'println("---:julia: Add CUDA to benchmarks environment")
          using Pkg
          Pkg.add("CUDA")'

      julia --project=benchmarks -e 'println("--- :julia: Run Benchmarks")
          include("benchmarks/runbenchmarks.jl")'
    artifact_paths:
      - "benchmarks/results/*"
    agents:
      queue: "benchmark"
      gpu: "rtx2070"
      cuda: "*"
    env:
      BENCHMARK_GROUP: CUDA
    timeout_in_minutes: 30

  - label: "KomaMRICore / Benchmark / Metal / Julia 1"
    key: "benchmark-metal"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=benchmarks -e 'println("--- :julia: Instantiating project")
          using Pkg
          Pkg.develop([
              PackageSpec(path=pwd(), subdir="KomaMRIBase"),
              PackageSpec(path=pwd(), subdir="KomaMRICore"),
          ])'

      julia --project=benchmarks -e 'println("---:julia: Add Metal to benchmarks environment")
          using Pkg
          Pkg.add("Metal")'

      julia --project=benchmarks -e 'println("--- :julia: Run Benchmarks")
          include("benchmarks/runbenchmarks.jl")'
    artifact_paths:
      - "benchmarks/results/*"
    agents:
      queue: "juliaecosystem"
      os: "macos"
      arch: "aarch64"
    env:
      BENCHMARK_GROUP: Metal
    timeout_in_minutes: 30

  - label: "KomaMRICore / Benchmark / oneAPI / Julia 1"
    key: "benchmark-oneapi"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=benchmarks -e 'println("--- :julia: Instantiating project")
          using Pkg
          Pkg.develop([
              PackageSpec(path=pwd(), subdir="KomaMRIBase"),
              PackageSpec(path=pwd(), subdir="KomaMRICore"),
          ])'

      julia --project=benchmarks -e 'println("---:julia: Add oneAPI to benchmarks environment")
          using Pkg
          devdir = mktempdir()
          withenv("JULIA_PKG_PRECOMPILE_AUTO" => 0,
                  "JULIA_PKG_DEVDIR" => devdir) do
              Pkg.develop("oneAPI")
              include(joinpath(devdir, "oneAPI", "deps", "build_ci.jl"))
          end'

      julia --project=benchmarks -e 'println("--- :julia: Run Benchmarks")
          using oneAPI
          oneAPI.versioninfo()
          include("benchmarks/runbenchmarks.jl")'
    artifact_paths:
      - "benchmarks/results/*"
    agents:
      queue: "juliagpu"
      intel: "*"
    env:
      BENCHMARK_GROUP: oneAPI
    soft_fail:
      - exit_status: "*"
    timeout_in_minutes: 30

  - label: "KomaMRICore / Benchmark / Combine"
    key: "benchmark-combine"
    depends_on:
      - "benchmark-cpu-1"
      - "benchmark-cpu-2"
      - "benchmark-cpu-4"
      - "benchmark-cpu-8"
      - "benchmark-amdgpu"
      - "benchmark-cuda"
      - "benchmark-metal"
      - "benchmark-oneapi"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      buildkite-agent artifact download "benchmarks/results/*" .

      julia --project=benchmarks -e 'println("--- :julia: Instantiating project")
          using Pkg
          Pkg.instantiate()'

      julia --project=benchmarks -e 'println("--- :julia: Combining Benchmarks")
          include("benchmarks/aggregate.jl")'
    artifact_paths:
      - "benchmarks/results/combinedbenchmarks.json"
    agents:
      queue: "juliagpu"
    timeout_in_minutes: 10
