name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: |
        Your feature may already be requested!
        Please search on the issue tracker before creating a new issue.
    validations:
      required: true
