pulseq_matlab = getenv('PULSEQ_MATLAB');
seq_path = getenv('PULSEQ_MATLAB_SEQ');
gamma = str2double(getenv('KOMA_GAMMA'));

addpath(genpath(pulseq_matlab));
sys = mr.opts('gamma', gamma, 'gradUnit', 'mT/m', 'maxGrad', 40, ...
    'slewUnit', 'T/m/s', 'maxSlew', 170, 'b1Unit', 'T', 'maxB1', 20e-6, ...
    'rfDeadTime', 80e-6, 'rfRingdownTime', 30e-6, 'adcDeadTime', 12e-6, ...
    'adcRasterTime', 100e-9, 'rfRasterTime', 1e-6, ...
    'gradRasterTime', 10e-6, 'blockDurationRaster', 10e-6);
seq = mr.Sequence(sys);

seq.addBlock(mr.makeTrapezoid('x', sys, 'area', gamma*2e-8));
seq.addBlock(mr.makeTrapezoid('x', sys, 'area', gamma*30e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'area', gamma*8e-6, 'duration', 1e-3));
seq.addBlock(mr.makeTrapezoid('x', sys, 'area', gamma*8e-6, 'duration', 1e-3, 'riseTime', 120e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'area', gamma*8e-6, 'duration', 1e-3, 'riseTime', 100e-6, 'fallTime', 130e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'flatArea', gamma*10e-6, 'flatTime', 0.8e-3));
seq.addBlock(mr.makeTrapezoid('x', sys, 'flatArea', gamma*10e-6, 'flatTime', 0.8e-3, 'riseTime', 90e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'flatArea', gamma*10e-6, 'flatTime', 0.8e-3, 'riseTime', 90e-6, 'fallTime', 110e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'amplitude', gamma*20e-3, 'flatTime', 0.8e-3));
seq.addBlock(mr.makeTrapezoid('x', sys, 'amplitude', gamma*20e-3, 'flatTime', 0.8e-3, 'riseTime', 120e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'amplitude', gamma*20e-3, 'flatTime', 0.8e-3, 'riseTime', 120e-6, 'fallTime', 130e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'amplitude', gamma*20e-3, 'duration', 1.2e-3));
seq.addBlock(mr.makeTrapezoid('x', sys, 'amplitude', gamma*20e-3, 'duration', 1.2e-3, 'riseTime', 120e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'amplitude', gamma*20e-3, 'duration', 1.2e-3, 'riseTime', 120e-6, 'fallTime', 130e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'area', -gamma*8e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'area', gamma*8e-6, 'delay', 40e-6));
seq.addBlock(mr.makeTrapezoid('x', sys, 'flatArea', gamma*6e-6, 'flatTime', 0.8e-3, 'maxGrad', gamma*30e-3, 'maxSlew', gamma*120));

seq.addBlock(mr.makeBlockPulse(pi/2, sys, 'duration', 1e-3, 'freqOffset', 123, 'phaseOffset', 0.3, 'use', 'excitation'));
seq.addBlock(mr.makeBlockPulse(pi/2, sys, 'bandwidth', 250, 'use', 'excitation'));
seq.addBlock(mr.makeBlockPulse(pi/2, sys, 'bandwidth', 500, 'timeBwProduct', 3, 'use', 'excitation'));
seq.addBlock(mr.makeBlockPulse(pi/2, sys, 'duration', 1e-3, 'delay', 20e-6, 'use', 'excitation'));
[rf] = mr.makeSincPulse(pi/2, sys, 'duration', 2e-3, 'use', 'excitation'); seq.addBlock(rf);
[rf] = mr.makeSincPulse(pi/2, sys, 'duration', 2.4e-3, 'freqOffset', 123, 'phaseOffset', 0.4, 'timeBwProduct', 6, 'apodization', 0.46, 'centerpos', 0.43, 'dwell', 2e-6, 'use', 'excitation'); seq.addBlock(rf);
[rf, gz, gzr] = mr.makeSincPulse(pi/2, sys, 'duration', 2e-3, 'sliceThickness', 5e-3, 'use', 'excitation'); seq.addBlock(rf, gz); seq.addBlock(gzr);
[rf, gz, gzr] = mr.makeSincPulse(pi/2, sys, 'duration', 2e-3, 'sliceThickness', 5e-3, 'delay', 20e-6, 'maxGrad', gamma*30e-3, 'maxSlew', gamma*120, 'use', 'excitation'); seq.addBlock(rf, gz); seq.addBlock(gzr);
seq.addBlock(mr.makeArbitraryRf([1, 2, 1], pi/4, sys, 'dwell', 200e-6, 'use', 'excitation'));
seq.addBlock(mr.makeArbitraryRf([1, 1i, 1, -1i], pi/4, sys, 'dwell', 100e-6, 'center', 150e-6, 'freqOffset', 77, 'phaseOffset', 0.2, 'delay', 20e-6, 'use', 'excitation'));
edgeRfFlip = 0.1*pi/180;
edgeRfRasterSamples = [1, 2, 1, 2, 1, 2, 1, 2, 1, 2];
seq.addBlock(mr.makeArbitraryRf(edgeRfRasterSamples, edgeRfFlip, sys, 'dwell', sys.rfRasterTime, 'use', 'excitation'));
rf = mr.makeArbitraryRf([1, 2, 1], edgeRfFlip, sys, 'dwell', sys.rfRasterTime, 'use', 'excitation');
timeShapeStart = 2*sys.rfRasterTime;
timeShapeIntervals = [3; 5]*sys.rfRasterTime;
timeShapeCenter = timeShapeStart + timeShapeIntervals(1);
rf.t = timeShapeStart + [0; cumsum(timeShapeIntervals)];
rf.shape_dur = ceil((rf.t(end)-eps)/sys.rfRasterTime)*sys.rfRasterTime;
rf.center = timeShapeCenter;
rf.delay = sys.rfDeadTime;
seq.addBlock(rf);
rf = mr.makeArbitraryRf([1, 2, 1], edgeRfFlip, sys, 'dwell', sys.rfRasterTime, 'use', 'excitation');
irregularTimeShapeStart = sys.rfRasterTime;
irregularTimeShapeIntervals = [2; 7]*sys.rfRasterTime;
irregularTimeShapeCenter = 3*sys.rfRasterTime;
rf.t = irregularTimeShapeStart + [0; cumsum(irregularTimeShapeIntervals)];
rf.shape_dur = ceil((rf.t(end)-eps)/sys.rfRasterTime)*sys.rfRasterTime;
rf.center = irregularTimeShapeCenter;
rf.delay = sys.rfDeadTime;
seq.addBlock(rf);
[rf, gz, gzr] = mr.makeArbitraryRf([1, 1, 1, 1], pi/2, sys, 'dwell', 100e-6, 'bandwidth', 2e3, 'sliceThickness', 5e-3, 'use', 'excitation'); sliceArea = gz.amplitude*rf.shape_dur; gzr = mr.makeTrapezoid('z', sys, 'Area', -sliceArea*(1-rf.center/rf.shape_dur)-0.5*(gz.area-sliceArea)); seq.addBlock(rf, gz); seq.addBlock(gzr);
[rf, gz, gzr] = mr.makeArbitraryRf([1, 1, 1, 1], pi/2, sys, 'dwell', 100e-6, 'timeBwProduct', 2, 'sliceThickness', 5e-3, 'use', 'excitation'); sliceArea = gz.amplitude*rf.shape_dur; gzr = mr.makeTrapezoid('z', sys, 'Area', -sliceArea*(1-rf.center/rf.shape_dur)-0.5*(gz.area-sliceArea)); seq.addBlock(rf, gz); seq.addBlock(gzr);
rf = mr.makeGaussPulse(pi/2, sys, 'duration', 2e-3, 'use', 'excitation'); seq.addBlock(rf);
rf = mr.makeGaussPulse(pi/2, sys, 'duration', 2e-3, 'bandwidth', 2e3, 'use', 'excitation'); seq.addBlock(rf);
seq.addBlock(mr.makeGaussPulse(pi/2, sys, 'duration', 2.4e-3, 'bandwidth', 1.8e3, 'apodization', 0.2, 'centerpos', 0.43, 'dwell', 2e-6, 'freqOffset', 123, 'phaseOffset', 0.4, 'delay', 20e-6, 'use', 'excitation'));
[rf, gz, gzr] = mr.makeGaussPulse(pi/2, sys, 'duration', 2e-3, 'bandwidth', 2e3, 'sliceThickness', 5e-3, 'use', 'excitation'); seq.addBlock(rf, gz); seq.addBlock(gzr);
[rf, gz, gzr] = mr.makeGaussPulse(pi/2, sys, 'duration', 2e-3, 'bandwidth', 2e3, 'sliceThickness', 5e-3, 'maxGrad', gamma*30e-3, 'maxSlew', gamma*120, 'use', 'excitation'); seq.addBlock(rf, gz); seq.addBlock(gzr);
rf = mr.makeSLRpulse(10*pi/180, 'system', sys); seq.addBlock(rf);
rf = mr.makeSLRpulse(pi/2, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6, 'filterType', 'pm'); seq.addBlock(rf);
rf = mr.makeSLRpulse(pi/2, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6, 'filterType', 'min'); seq.addBlock(rf);
rf = mr.makeSLRpulse(pi/2, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6, 'filterType', 'max'); seq.addBlock(rf);
rf = mr.makeSLRpulse(pi/2, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6, 'filterType', 'ls'); seq.addBlock(rf);
rf = mr.makeSLRpulse(pi/6, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6); seq.addBlock(rf);
rf = mr.makeSLRpulse(pi/6 + eps(pi/6), 'system', sys, 'duration', 5.6e-3, 'dwell', 8e-6); seq.addBlock(rf);
rf = mr.makeSLRpulse(-pi/2, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6); seq.addBlock(rf);
rf = mr.makeSLRpulse(pi, 'system', sys, 'duration', 4e-3, 'dwell', 100e-6, 'use', 'refocusing'); seq.addBlock(rf);
rf = mr.makeSLRpulse(pi, 'system', sys, 'duration', 4.6e-3, 'dwell', 25e-6, 'use', 'inversion'); seq.addBlock(rf);
rf = mr.makeSLRpulse(110*pi/180, 'system', sys, 'duration', 5.6e-3, 'dwell', 8e-6, 'use', 'saturation'); seq.addBlock(rf);
rf = mr.makeSLRpulse(pi/2, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6, 'use', 'preparation'); seq.addBlock(rf);
rf = mr.makeSLRpulse(80*pi/180, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6, 'use', 'other'); seq.addBlock(rf);
rf = mr.makeSLRpulse(70*pi/180, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6, 'use', 'undefined'); seq.addBlock(rf);
% The half-sample duration requires block-raster rounding before write.
rf = mr.makeSLRpulse(pi/2, 'system', sys, 'duration', 500.5*8e-6, 'dwell', 8e-6); seq.addBlock('roundUpBlockDuration', rf);
[rf, gz, gzr] = mr.makeSLRpulse(pi/2, 'system', sys, 'duration', 5.6e-3, 'dwell', 8e-6, 'sliceThickness', 5e-3); seq.addBlock(rf, gz); seq.addBlock(gzr);
[rf, gz, gzr] = mr.makeSLRpulse(pi/2, 'system', sys, 'duration', 4e-3, 'dwell', 8e-6, 'timeBwProduct', 6, 'sliceThickness', 5e-3, 'freqOffset', 123, 'phaseOffset', 0.4, 'delay', 120e-6, 'maxGrad', gamma*30e-3, 'maxSlew', gamma*120); seq.addBlock(rf, gz); seq.addBlock(gzr);
seq.addBlock(mr.makeAdc(16, sys, 'dwell', 1e-6));
seq.addBlock(mr.makeAdc(16, sys, 'dwell', 1e-6, 'freqOffset', 77, 'phaseOffset', 0.2));
seq.addBlock(mr.makeAdc(16, sys, 'duration', 16e-6));
seq.addBlock(mr.makeAdc(16, sys, 'dwell', 1e-6, 'delay', 4e-6));
seq.addBlock(mr.makeAdc(4, sys, 'duration', 16e-6));
seq.addBlock(mr.makeDelay(0));
seq.addBlock(mr.makeDelay(1.5e-3));
seq.addBlock(mr.makeLabel('SET', 'LIN', 3));
seq.addBlock(mr.makeLabel('INC', 'SLC', -2));
seq.addBlock(mr.makeLabel('SET', 'REF', true));
seq.addBlock(mr.makeRotation(pi/3));
seq.addBlock(mr.makeRotation(-pi/4, pi/6));
seq.addBlock(mr.makeRotation([1 2 3], pi/5));
seq.addBlock(mr.makeRotation([-1 0 0], -pi/6));
seq.addBlock(mr.makeRotation([0.5 0.5 -0.5 0.5]));
seq.addBlock(mr.makeRotation([0 -1 0; 1 0 0; 0 0 1]));
seq.addBlock(mr.makeTrigger('physio1', 'system', sys));
seq.addBlock(mr.makeTrigger('physio2', 'delay', 20e-6, 'duration', 100e-6, 'system', sys));
seq.addBlock(mr.makeDigitalOutputPulse('osc0', 'system', sys));
seq.addBlock(mr.makeDigitalOutputPulse('osc1', 'delay', 20e-6, 'duration', 100e-6, 'system', sys));
seq.addBlock(mr.makeDigitalOutputPulse('ext1', 'duration', 200e-6, 'system', sys));
seq.addBlock(mr.makeArbitraryGrad('x', gamma*[0; 1e-3; 0], sys, 'first', 0, 'last', 0));
seq.addBlock(mr.makeArbitraryGrad('x', gamma*[0; 0.5e-3; 1e-3; 0.5e-3; 0], sys, 'first', 0, 'last', 0, 'delay', 20e-6));
seq.addBlock(mr.makeArbitraryGrad('x', gamma*[0; 0.2e-3; 0.4e-3; 0.2e-3; 0], sys, 'oversampling', true, 'first', 0, 'last', 0));
seq.addBlock(mr.makeExtendedTrapezoid('x', sys, 'times', [0, 0.5e-3, 1e-3], 'amplitudes', gamma*[0, 1e-3, 0]));
g = mr.makeExtendedTrapezoid('x', sys, 'times', [20e-6, 0.5e-3, 1e-3], 'amplitudes', gamma*[0, 1e-3, 0]); seq.addBlock(g);
g = mr.makeExtendedTrapezoid('x', sys, 'times', [20e-6, 0.5e-3, 1e-3], 'amplitudes', gamma*[0, 2e-3, 0]); seq.addBlock(g);
waveform = mr.pts2waveform([0, 0.355e-3, 1e-3], gamma*[0, 1e-3, 0], sys.gradRasterTime);
seq.addBlock(mr.makeArbitraryGrad('x', waveform, sys, 'first', 0, 'last', 0));
[g, t, a] = mr.makeExtendedTrapezoidArea('x', 0, 0, gamma*10e-6, sys); seq.addBlock(g);
prep = mr.makeExtendedTrapezoid('x', sys, 'times', [0, 100e-6], 'amplitudes', gamma*[0, 10e-3]);
[g, t, a] = mr.makeExtendedTrapezoidArea('x', gamma*10e-3, gamma*5e-3, gamma*2e-6, sys); seq.addBlock(prep); seq.addBlock(g);
[g, t, a] = mr.makeExtendedTrapezoidArea('x', gamma*5e-3, 0, -gamma*5e-6, sys); seq.addBlock(g);

seq.write(seq_path);
