name: Benchmarks
on: 
  pull_request:
    branches:
      - main
    paths:
      - "KomaMRICore/src/**/*"
      - "KomaMRICore/ext/**/*"
      - "KomaMRICore/Project.toml"
      - "KomaMRIBase/src/**/*"
      - "KomaMRIBase/Project.toml"
      - "bench/**/*"
      - ".buildkite/**/*"
      - "Project.toml"
  push:
    branches:
      - main
      - benchmark #TO-DO: remove this
    paths:
      - "KomaMRICore/src/**/*"
      - "KomaMRICore/ext/**/*"
      - "KomaMRICore/Project.toml"
      - "KomaMRIBase/src/**/*"
      - "KomaMRIBase/Project.toml"
      - "bench/**/*"
      - ".buildkite/**/*"
      - "Project.toml"
      - ".github/**/*" #TO-DO: remove this

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Download Buildkite Artifacts
        id: download
        uses: EnricoMi/download-buildkite-artifact-action@v1
        with:
          buildkite_token: ${{ secrets.BUILDKITE_TOKEN }}
          ignore_build_states: blocked,canceled,skipped,not_run,failed
          ignore_job_states: timed_out,failed
          output_path: artifacts
          log_level: DEBUG #TO-DO: remove this

      - name: Locate Benchmarks Artifact
        id: locate
        if: ${{ steps.download.download_state == 'success'}}
        run: echo "path=$(find artifacts -type f -name combinedbenchmarks.json)" >> $GITHUB_OUTPUT


      - name: Upload Benchmark Results
        if: ${{ steps.download.download_state == 'success' && steps.locate.path != '' }}
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: KomaMRI Benchmarks
          tool: 'julia'
          output-file-path: ${{ steps.locate.path }}
          summary-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
          alert-threshold: "150%"
          fail-on-alert: false
          auto-push: ${{ github.event_name != 'pull_request' }}
