name: CI - KomaMRICore
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci-core.yml'
      - 'KomaMRICore/**'
      - 'KomaMRIBase/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/ci-core.yml'
      - 'KomaMRICore/**'
      - 'KomaMRIBase/**'
jobs:
  test:
    if: ${{ (github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')) && (github.event_name != 'pull_request' || github.event.pull_request.draft == false) }}
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version: ['1.10', '1']
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64]
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: "KomaMRICore: Development Setup"
        if: '!cancelled()'
        shell: bash
        run: |
          julia --color=yes --project="KomaMRICore" -e "using Pkg; Pkg.develop(PackageSpec(; path=\"./KomaMRIBase\"));"
      - name: "KomaMRICore: Build"
        if: '!cancelled()'
        uses: julia-actions/julia-buildpkg@v1
        with:
          project: KomaMRICore
      - name: "KomaMRICore: Run Tests"
        if: '!cancelled()'
        uses: julia-actions/julia-runtest@v1
        with:
          project: KomaMRICore
      - uses: julia-actions/julia-processcoverage@v1
        if: '!cancelled()'
        with:
          directories: KomaMRICore/src,KomaMRICore/ext
      - uses: codecov/codecov-action@v5
        if: '!cancelled()'
        with:
          files: lcov.info
          flags: core
          token: ${{ secrets.CODECOV_TOKEN }}
