name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        run: julia -e 'using CompatHelper; CompatHelper.main(; subdirs=["", "KomaMRICore", "KomaMRIFiles", "KomaMRIPlots"])'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}