name: Docs
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'examples/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'examples/**'
jobs:
  docs:
    if: ${{ (github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')) && (github.event_name != 'pull_request' || github.event.pull_request.draft == false) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: "Documentation dev environment setup"
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop([
                PackageSpec(path=pwd(), subdir="."),
                PackageSpec(path=pwd(), subdir="KomaMRIBase"),
                PackageSpec(path=pwd(), subdir="KomaMRICore"),
                PackageSpec(path=pwd(), subdir="KomaMRIFiles"),
                PackageSpec(path=pwd(), subdir="KomaMRIPlots")
            ])
            Pkg.instantiate()'
      - name: "Testing documentation (doctest)"
        run: |
          julia --project=docs -e '
            using Documenter: doctest
            using KomaMRI
            doctest(KomaMRI)'
      - name: "Building documentation (docs/make.jl)"
        if: ${{ github.event_name == 'push' }}
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      - name: "Building documentation (docs/make.jl) - [PR] PUSH_PREVIEW"
        if: ${{ github.event_name == 'pull_request' }}
        run: julia --project=docs docs/make.jl push_preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
